# Created module for recognizing audio from file or microphone as input
# Simply it is a CLI module I have created, so just run this file, and ..
# try to import necessary packages
try:
    import speech_recognition, pyaudio
# if module not installed than, import os and run command from 'pip install <PACKAGES...>'
except ModuleNotFoundError:
    import os
    # microphone uses pyaudio so we need to install pyaudio also..
    os.system('pip install SpeechRecognition pyAudio')

# internet error shows when, internet not connected
internetERROR = 'ERROR: not able to understand please check your internet connection then try again'

# now import speech recognition again in current context as speech_r alise
import speech_recognition as speech_r

# define instance of recognizer
audioRecognizer = speech_r.Recognizer()

# define fuction for converting audio file to text string
def audioToText(audiofile):
    try: 
        # try to run these program, if file not found encountered -> shows file not found, except for
        # all shows internet error

        # read audio file as argument audiofile
        with speech_r.AudioFile(audiofile) as audioPlay:

            recordStr = audioRecognizer.record(audioPlay)
            # I have use here google recognizer without any key or user pass
            # another API also use key, user and passwd
            text = audioRecognizer.recognize_google(recordStr)
        # recgniser convert audio data to text string and return
        return text
    except FileNotFoundError:
        print(f'ERROR: file {audiofile} not found..')
    except:
        print(internetERROR)

# define function for use accept audio from microphone
def listening(language='en-US'):
    try: 
        sentence = '' # empty variable for storing final data
        # open microphone, return error "if pyaudio not installed"
        with speech_r.Microphone() as input:
            audioRecognizer.adjust_for_ambient_noise(input) # remove background voice or noise
            audio = audioRecognizer.listen(input) # listen make audio data 
            try:
                # rcognize audio...
                sentence = audioRecognizer.recognize_google(audio, language=language)
            except Exception:
                sentence = ''
        return sentence
    except Exception:
        # if any type of error occure than it will shows internet error
        return print(internetERROR)

# main program called .....
print("Welcome to my AudioHandler\nChoose your input as type:\n1 for Audio File\n2 for Microphone")

# input takes option if you have audio file in wav/mp3 format
# so take option 1 and if you try it with your own voice 
# than you can choose 2 open "Microphone"
inputhand = int(input("Enter either 1 or 2 only: "))

if (inputhand == 1):
    # if user choose 1, it will generate a input for acceptance of full path of audio file
    audioFil = str(input("Enter full path of your mp3/wav file: "))
    # than, print text generated by audio file
    print(audioToText(audiofile=audioFil))

# if user choose 2 on inputhand variable, it will open microphone..
elif (inputhand == 2):
    # and return text, what you are saying..
    print(listening())

else:
    # shows error if user enter any other number except 1 or 2
    print('ERROR: Invalid input founded, you can type either one or two, only')